apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  ##googleCloudBuild:
  ##  projectId: id-project
  artifacts:
    # - image: us.gcr.io/id-project/auth # for google cloud build adn commend local push
    - image: sanpedrofabianezequiel/auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sanpedrofabianezequiel/client
      context: ./client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: sanpedrofabianezequiel/tickets
      context: ./tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .